Uygulama24/Models/ErrorViewModel.cs
namespace Uygulama24.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Uygulama24/Models/Uyelerim.cs
namespace Uygulama24.Models
{
    public class Uyelerim
    {
        public int Id { get; set; }
        public string kul { get; set; }
        public string sifre { get; set; }
    }
}

Uygulama24/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Uygulama24.Models;

namespace Uygulama24.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Uygulama24/Controllers/UyeController.cs
using Microsoft.AspNetCore.Mvc;
using Uygulama24.Models;

namespace Uygulama24.Controllers
{
    public class UyeController : Controller
    {
        List<Uyelerim> datam = new List<Uyelerim>() {
         new Uyelerim{ Id=1,kul="Kadir",sifre="123"},
         new Uyelerim{ Id=2,kul="Amine",sifre="123"},
         new Uyelerim{ Id=3,kul="Selen",sifre="123"},
         new Uyelerim{ Id=4,kul="Abdullah",sifre="123"},
         new Uyelerim{ Id=5,kul="Hakkı",sifre="123"},
        };
        public IActionResult Index()
        {
            var listem = datam.ToList();
            return View(listem);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(string kul, string sifre)
        {
            if(kul=="Admin" && sifre=="1234")
            {
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Kullanıcı veya Şifre Hatalı";
            }
            return View();
        }
        [HttpGet]
        public IActionResult Goster(int Id)
        {
            ViewBag.Deger = Id;
            return View();
        }
    }
}

Uygulama24/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Uygulama24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Uygulama24</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Uygulama24.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Uygulama24</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Uygulama24 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Uygulama24/Views/Uye/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<form method="post" action="Create">
    <div class="form-group">
        <input type="text" name="kul" class="form-control" placeholder="Kullanıcı Adını girin" />
        <input type="text" name="sifre" class="form-control" placeholder="Şifrenizi girin" />
    </div>
    <div class="form-group">
        <input type="submit" value="Gönder" class="btn btn-primary" />
    </div>
</form>
@{
    if(TempData["Error"]!=null)
    {
        <h1>TempData["Error"]</h1>
    }
}

Uygulama24/Views/Uye/Goster.cshtml
@{
    ViewData["Title"] = "Goster";
}

<h1>Goster</h1>

<h1>@ViewBag.Deger</h1>

Uygulama24/Views/Uye/Index.cshtml
@model List<Uygulama24.Models.Uyelerim>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<a href="/Uye/Create">Yeni Üye</a>
<a asp-action="Create" asp-controller="Uye">Yeni Üye</a>
<a asp-action="Goster" asp-controller="Home" asp-route-Id="3">Sayı</a>
@foreach(var item in Model)
{
    <p>Kullanıcı Adı: @item.kul Şifre:@item.sifre </p>
}